repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: postgres
    chart: ./charts/postgres
    values:
      - ./values/pocketflow-postgres.yaml

  - name: pocketflow-backend
    chart: ./charts/app
    values:
      - ./values/pocketflow-backend.yaml

  - name: pocketflow-frontend
    chart: ./charts/app
    values:
      - ./values/pocketflow-frontend.yaml

  - name: ingress-backend
    chart: stable/nginx-ingress
    version: 1.36.0

  - name: ingress-controller
    chart: ./charts/ingress
    values:
      - ./values/ingress.yaml
