# Generated by Django 3.1 on 2020-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('result', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'archive',
                'ordering': ['id'],
            },
        ),
    ]
