apiVersion: v1
name: postgres
description: A Helm chart for PostgreSQL database
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - database
  - postgres
maintainers:
  - name: Yuki Iburi
    url: https://github.com/iburi52