apiVersion: v1
name: app
description: A Helm chart for any application
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - app
  - backend
  - django
  - frontend
  - angular
maintainers:
  - name: Yuki Iburi
    url: https://github.com/iburi52